{{- if .Values.credentialPlugin.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "capi-controller.fullname" . }}-credential-providers
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "capi-controller.labels" . | nindent 4 }}
data:
  provider-config.json: |
    {
      "providers": [
        {
          "name": "kubeconfig-secretreader",
          "execConfig": {
            "apiVersion": "client.authentication.k8s.io/v1",
            "command": "/plugins/bin/kubeconfig-secretreader-plugin",
            "args": null,
            "env": null,
            "provideClusterInfo": true
          }
        }
      ]
    }
{{- end }}
