{{- if .Values.webhooks.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "capi-controller.fullname" . }}-webhook
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "capi-controller.labels" . | nindent 4 }}
spec:
  ports:
    - port: 443
      targetPort: webhook
      protocol: TCP
      name: https
  selector:
    {{- include "capi-controller.selectorLabels" . | nindent 4 }}
{{- end }}
