{{- if ne .Values.tls.method "certmanager" }}
{{- $_ := include "addon-webhook.tls.setup" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "addon-webhook.fullname" . }}-ca
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "addon-webhook.labels" . | nindent 4 }}
type: Opaque
data:
  ca.crt: {{ .addonCA.Cert | b64enc }}
  ca.key: {{ .addonCA.Key | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "addon-webhook.fullname" . }}-tls
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "addon-webhook.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  ca.crt: {{ .addonCA.Cert | b64enc }}
  tls.crt: {{ .addonTLSCrt }}
  tls.key: {{ .addonTLSKey }}
{{- end }}
