apiVersion: v1
kind: Service
metadata:
  name: {{ include "addon-webhook.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "addon-webhook.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: webhook
      port: 443
      targetPort: webhook
