/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
	apisv1alpha1 "sigs.k8s.io/cluster-inventory-api/apis/v1alpha1"
	scheme "sigs.k8s.io/cluster-inventory-api/client/clientset/versioned/scheme"
)

// AddonsGetter has a method to return a AddonInterface.
// A group's client should implement this interface.
type AddonsGetter interface {
	Addons(namespace string) AddonInterface
}

// AddonInterface has methods to work with Addon resources.
type AddonInterface interface {
	Create(ctx context.Context, addon *apisv1alpha1.Addon, opts v1.CreateOptions) (*apisv1alpha1.Addon, error)
	Update(ctx context.Context, addon *apisv1alpha1.Addon, opts v1.UpdateOptions) (*apisv1alpha1.Addon, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, addon *apisv1alpha1.Addon, opts v1.UpdateOptions) (*apisv1alpha1.Addon, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*apisv1alpha1.Addon, error)
	List(ctx context.Context, opts v1.ListOptions) (*apisv1alpha1.AddonList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *apisv1alpha1.Addon, err error)
	AddonExpansion
}

// addons implements AddonInterface
type addons struct {
	*gentype.ClientWithList[*apisv1alpha1.Addon, *apisv1alpha1.AddonList]
}

// newAddons returns a Addons
func newAddons(c *ApisV1alpha1Client, namespace string) *addons {
	return &addons{
		gentype.NewClientWithList[*apisv1alpha1.Addon, *apisv1alpha1.AddonList](
			"addons",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *apisv1alpha1.Addon { return &apisv1alpha1.Addon{} },
			func() *apisv1alpha1.AddonList { return &apisv1alpha1.AddonList{} },
		),
	}
}
