/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
	apisv1alpha1 "sigs.k8s.io/cluster-inventory-api/apis/v1alpha1"
	scheme "sigs.k8s.io/cluster-inventory-api/client/clientset/versioned/scheme"
)

// AddonClassesGetter has a method to return a AddonClassInterface.
// A group's client should implement this interface.
type AddonClassesGetter interface {
	AddonClasses(namespace string) AddonClassInterface
}

// AddonClassInterface has methods to work with AddonClass resources.
type AddonClassInterface interface {
	Create(ctx context.Context, addonClass *apisv1alpha1.AddonClass, opts v1.CreateOptions) (*apisv1alpha1.AddonClass, error)
	Update(ctx context.Context, addonClass *apisv1alpha1.AddonClass, opts v1.UpdateOptions) (*apisv1alpha1.AddonClass, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, addonClass *apisv1alpha1.AddonClass, opts v1.UpdateOptions) (*apisv1alpha1.AddonClass, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*apisv1alpha1.AddonClass, error)
	List(ctx context.Context, opts v1.ListOptions) (*apisv1alpha1.AddonClassList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *apisv1alpha1.AddonClass, err error)
	AddonClassExpansion
}

// addonClasses implements AddonClassInterface
type addonClasses struct {
	*gentype.ClientWithList[*apisv1alpha1.AddonClass, *apisv1alpha1.AddonClassList]
}

// newAddonClasses returns a AddonClasses
func newAddonClasses(c *ApisV1alpha1Client, namespace string) *addonClasses {
	return &addonClasses{
		gentype.NewClientWithList[*apisv1alpha1.AddonClass, *apisv1alpha1.AddonClassList](
			"addonclasses",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *apisv1alpha1.AddonClass { return &apisv1alpha1.AddonClass{} },
			func() *apisv1alpha1.AddonClassList { return &apisv1alpha1.AddonClassList{} },
		),
	}
}
