/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
	apisv1alpha1 "sigs.k8s.io/cluster-inventory-api/apis/v1alpha1"
)

// AddonClassLister helps list AddonClasses.
// All objects returned here must be treated as read-only.
type AddonClassLister interface {
	// List lists all AddonClasses in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*apisv1alpha1.AddonClass, err error)
	// AddonClasses returns an object that can list and get AddonClasses.
	AddonClasses(namespace string) AddonClassNamespaceLister
	AddonClassListerExpansion
}

// addonClassLister implements the AddonClassLister interface.
type addonClassLister struct {
	listers.ResourceIndexer[*apisv1alpha1.AddonClass]
}

// NewAddonClassLister returns a new AddonClassLister.
func NewAddonClassLister(indexer cache.Indexer) AddonClassLister {
	return &addonClassLister{listers.New[*apisv1alpha1.AddonClass](indexer, apisv1alpha1.Resource("addonclass"))}
}

// AddonClasses returns an object that can list and get AddonClasses.
func (s *addonClassLister) AddonClasses(namespace string) AddonClassNamespaceLister {
	return addonClassNamespaceLister{listers.NewNamespaced[*apisv1alpha1.AddonClass](s.ResourceIndexer, namespace)}
}

// AddonClassNamespaceLister helps list and get AddonClasses.
// All objects returned here must be treated as read-only.
type AddonClassNamespaceLister interface {
	// List lists all AddonClasses in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*apisv1alpha1.AddonClass, err error)
	// Get retrieves the AddonClass from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*apisv1alpha1.AddonClass, error)
	AddonClassNamespaceListerExpansion
}

// addonClassNamespaceLister implements the AddonClassNamespaceLister
// interface.
type addonClassNamespaceLister struct {
	listers.ResourceIndexer[*apisv1alpha1.AddonClass]
}
